-- MySQL Script generated by MySQL Workbench
-- Wed Nov 13 14:31:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mario` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mario` ;

-- -----------------------------------------------------
-- Table `mario`.`active_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mario`.`active_orders` ;

CREATE TABLE IF NOT EXISTS `mario`.`active_orders` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `total_price` DOUBLE NOT NULL,
  `pickup_time` DATETIME NOT NULL,
  `customer_phone` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mario`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mario`.`customers` ;

CREATE TABLE IF NOT EXISTS `mario`.`customers` (
  `customer_name` VARCHAR(45) NULL DEFAULT '',
  `customer_phone` INT(11) NOT NULL,
  PRIMARY KEY (`customer_phone`),
  UNIQUE INDEX `customer_phone_UNIQUE` (`customer_phone` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mario`.`orderlines_pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mario`.`orderlines_pizzas` ;

CREATE TABLE IF NOT EXISTS `mario`.`orderlines_pizzas` (
  `orderline_id` INT(11) NOT NULL AUTO_INCREMENT,
  `order_id` INT(11) NOT NULL,
  `pizza_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`orderline_id`),
  UNIQUE INDEX `orderline_id_UNIQUE` (`orderline_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mario`.`orderlines_toppings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mario`.`orderlines_toppings` ;

CREATE TABLE IF NOT EXISTS `mario`.`orderlines_toppings` (
  `orderline_topping_id` INT(11) NOT NULL AUTO_INCREMENT,
  `topping_id` INT(11) NULL DEFAULT NULL,
  `orderline_id` INT(11) NOT NULL,
  PRIMARY KEY (`orderline_topping_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mario`.`pizza_toppings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mario`.`pizza_toppings` ;

CREATE TABLE IF NOT EXISTS `mario`.`pizza_toppings` (
  `pizza_id` INT(11) NOT NULL,
  `toppings_id` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mario`.`pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mario`.`pizzas` ;

CREATE TABLE IF NOT EXISTS `mario`.`pizzas` (
  `pizza_id` INT(11) NOT NULL,
  `pizza_name` VARCHAR(45) NOT NULL,
  `pizza_price` DOUBLE NOT NULL,
  PRIMARY KEY (`pizza_id`),
  UNIQUE INDEX `name_UNIQUE` (`pizza_name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`pizza_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mario`.`saved_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mario`.`saved_orders` ;

CREATE TABLE IF NOT EXISTS `mario`.`saved_orders` (
  `order_id` INT(11) NOT NULL,
  `total_price` DOUBLE NULL DEFAULT NULL,
  `order_time` VARCHAR(45) NULL DEFAULT NULL,
  `customer_phone` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`order_id`),
  INDEX `customer_phone_idx` (`customer_phone` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mario`.`saved_orders_pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mario`.`saved_orders_pizzas` ;

CREATE TABLE IF NOT EXISTS `mario`.`saved_orders_pizzas` (
  `saved_order_id` INT(11) NOT NULL,
  `pizza_name` VARCHAR(45) NOT NULL,
  `pizza_topping` VARCHAR(500) NOT NULL,
  `pizza_price` INT(11) NOT NULL,
  PRIMARY KEY (`saved_order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mario`.`toppings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mario`.`toppings` ;

CREATE TABLE IF NOT EXISTS `mario`.`toppings` (
  `toppings_id` INT(11) NOT NULL,
  `topping_name` VARCHAR(45) NOT NULL,
  `topping_price` DOUBLE NOT NULL,
  PRIMARY KEY (`toppings_id`),
  UNIQUE INDEX `ToppingName_UNIQUE` (`topping_name` ASC) VISIBLE,
  UNIQUE INDEX `IdToppings_UNIQUE` (`toppings_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
